# Generated by Django 5.2 on 2025-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmember',
            name='na_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
