# Generated by Django 5.2 on 2025-06-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='is_homeclass',
            new_name='is_home_class',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='shortname',
            new_name='short_name',
        ),
    ]
