# Generated by Django 5.2 on 2025-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_rename_is_homeclass_class_is_home_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='detailed_info',
            new_name='registration_data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='na_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
