# Generated by Django 5.2 on 2025-06-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_rename_detailed_info_student_registration_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='form_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nisn',
            field=models.CharField(default='000000000000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admission.registration', unique=True),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('registration_data', 'nisn', 'is_active'), name='unique_student_data'),
        ),
    ]
