# Generated by Django 5.2 on 2025-06-22 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_alter_registration_form_no_alter_student_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.registration'),
        ),
    ]
