# Generated by Django 5.2 on 2025-06-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_alter_student_registration_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classmember',
            constraint=models.UniqueConstraint(fields=('class_id', 'student_id', 'is_active'), name='unique_class_members'),
        ),
    ]
