# Generated by Django 5.2 on 2025-06-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0008_classmember_unique_class_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100, unique=True)),
                ("address1", models.CharField(max_length=100)),
                ("address2", models.CharField(max_length=100)),
                ("district1", models.CharField(max_length=100)),
                ("district2", models.CharField(max_length=100)),
                ("city_name", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_name", models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
