# Generated by Django 5.2 on 2025-06-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0009_schooldata_schoollevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoollevel",
            name="short_name",
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
