# Generated by Django 5.2 on 2025-06-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0010_schoollevel_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "level_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.schoollevel",
                    ),
                ),
                (
                    "school_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.schooldata",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school_id", "level_id", "full_name"),
                        name="unique_head_masters",
                    )
                ],
            },
        ),
    ]
