# Generated by Django 5.2 on 2025-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0012_teacher_user_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classmember",
            name="unique_class_members",
        ),
        migrations.RemoveConstraint(
            model_name="headmaster",
            name="unique_head_masters",
        ),
        migrations.RenameField(
            model_name="class",
            old_name="year",
            new_name="academic_year",
        ),
        migrations.RenameField(
            model_name="classmember",
            old_name="class_id",
            new_name="kelas",
        ),
        migrations.RenameField(
            model_name="classmember",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="headmaster",
            old_name="level_id",
            new_name="level",
        ),
        migrations.RenameField(
            model_name="headmaster",
            old_name="school_id",
            new_name="school",
        ),
        migrations.RenameField(
            model_name="learningperiod",
            old_name="year",
            new_name="academic_year",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="classmember",
            constraint=models.UniqueConstraint(
                fields=("kelas", "student", "is_active"), name="unique_class_members"
            ),
        ),
        migrations.AddConstraint(
            model_name="headmaster",
            constraint=models.UniqueConstraint(
                fields=("school", "level", "full_name"), name="unique_head_masters"
            ),
        ),
    ]
