# Generated by Django 5.2 on 2025-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0014_religion_remove_registration_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_name", models.CharField(max_length=25, unique=True)),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=4, null=True, unique=True),
                ),
            ],
        ),
    ]
