# Generated by Django 5.2 on 2025-12-18 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0015_gradelevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradelevel",
            name="school_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.schoollevel",
            ),
            preserve_default=False,
        ),
    ]
