# Generated by Django 5.2 on 2026-03-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0016_gradelevel_school_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradelevel",
            options={
                "verbose_name": "Grade Level",
                "verbose_name_plural": "Grade Levels",
            },
        ),
        migrations.AlterModelOptions(
            name="schoollevel",
            options={
                "verbose_name": "School Level",
                "verbose_name_plural": "School Levels",
            },
        ),
    ]
