# Generated by Django 5.1.3 on 2025-12-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_remove_gradelevel_school_level_and_more'),
        ('gradebook', '0024_remove_historicalassignmenthead_assignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeLevel',
        ),
    ]
