# Generated by Django 5.1.3 on 2025-12-22 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_delete_gradelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoollevel',
            options={'verbose_name': 'School Level', 'verbose_name_plural': 'School Levels'},
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='middle_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='place_of_birth',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='schoollevel',
            name='level_name',
            field=models.CharField(default='--', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='place_of_birth',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=25, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.schoollevel')),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
            },
        ),
    ]
