# Generated by Django 5.1.3 on 2025-12-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_alter_schoollevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='place_of_birth',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='place_of_birth',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
