# Generated by Django 5.1.3 on 2025-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_alter_registration_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoollevel',
            options={},
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='schoollevel',
            name='level_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
