# Generated by Django 5.2 on 2025-06-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_classmember_na_date'),
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('shortname', models.CharField(max_length=6)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('na_date', models.DateField(blank=True, null=True)),
                ('na_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
            ],
        ),
    ]
