# Generated by Django 5.2 on 2025-06-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='shortname',
            new_name='short_name',
        ),
    ]
