# Generated by Django 5.2 on 2025-06-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_classmember_unique_class_members'),
        ('gradebook', '0004_rename_shortname_course_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.assignmenttype')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.academicyear')),
            ],
        ),
    ]
