# Generated by Django 5.2 on 2025-06-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0005_assignmenttype_alter_subject_subject_name_weighting"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weighting",
            old_name="year",
            new_name="academic_year",
        ),
    ]
