# Generated by Django 5.2 on 2025-06-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0011_headmaster"),
        ("gradebook", "0006_rename_year_weighting_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="weighting",
            name="level_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.schoollevel",
            ),
        ),
        migrations.CreateModel(
            name="PassingGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passing_grade", models.IntegerField()),
                (
                    "level_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.schoollevel",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.subject",
                    ),
                ),
                (
                    "year_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.academicyear",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year_id", "subject_id", "level_id"),
                        name="unique_passing_grades",
                    )
                ],
            },
        ),
    ]
