# Generated by Django 5.2 on 2025-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0013_remove_classmember_unique_class_members_and_more"),
        ("gradebook", "0008_gradeentry"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="passinggrade",
            name="unique_passing_grades",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="year",
            new_name="academic_year",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="subject_id",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="coursemember",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="coursemember",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="passinggrade",
            old_name="year_id",
            new_name="academic_year",
        ),
        migrations.RenameField(
            model_name="passinggrade",
            old_name="level_id",
            new_name="level",
        ),
        migrations.RenameField(
            model_name="passinggrade",
            old_name="subject_id",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="weighting",
            old_name="assignment_id",
            new_name="assignment",
        ),
        migrations.RenameField(
            model_name="weighting",
            old_name="level_id",
            new_name="level",
        ),
        migrations.RenameField(
            model_name="weighting",
            old_name="subject_id",
            new_name="subject",
        ),
        migrations.AddConstraint(
            model_name="passinggrade",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "subject", "level"),
                name="unique_passing_grades",
            ),
        ),
    ]
