# Generated by Django 5.2 on 2025-10-28 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0013_remove_classmember_unique_class_members_and_more"),
        ("gradebook", "0009_remove_passinggrade_unique_passing_grades_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeentry",
            name="school_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.schoollevel",
            ),
        ),
        migrations.CreateModel(
            name="AssignmentHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("topic", models.TextField(blank=True, null=True)),
                ("max_score", models.IntegerField(default=100)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.assignmenttype",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=2),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("na_date", models.DateField(blank=True, null=True)),
                ("na_reason", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.student",
                    ),
                ),
                (
                    "assignment_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.assignmenthead",
                    ),
                ),
            ],
        ),
    ]
