# Generated by Django 5.2 on 2025-10-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0010_gradeentry_school_level_assignmenthead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
