# Generated by Django 5.2 on 2025-10-30 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0011_alter_subject_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeentry",
            name="assignment_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.assignmenttype",
            ),
            preserve_default=False,
        ),
    ]
