# Generated by Django 5.2 on 2025-10-30 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0012_gradeentry_assignment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.datetime(2025, 10, 30, 0, 0)),
        ),
        migrations.AddField(
            model_name="gradeentry",
            name="assignment_topic",
            field=models.CharField(default="to be fill later.", max_length=100),
        ),
    ]
