# Generated by Django 5.1.3 on 2025-11-28 04:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_remove_classmember_unique_class_members_and_more'),
        ('gradebook', '0013_gradeentry_assignment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 28, 0, 0)),
        ),
        migrations.CreateModel(
            name='ReportcardGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(default=0)),
                ('final_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.academicyear')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admission.schoollevel')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.learningperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.subject')),
            ],
        ),
    ]
