# Generated by Django 5.2 on 2025-11-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0013_remove_classmember_unique_class_members_and_more"),
        ("gradebook", "0014_alter_gradeentry_assignment_date_reportcardgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcardgrade",
            name="period",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.learningperiod",
            ),
            preserve_default=False,
        ),
    ]
