# Generated by Django 5.2 on 2025-11-11 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0015_reportcardgrade_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.datetime(2025, 11, 11, 0, 0)),
        ),
        migrations.AlterField(
            model_name="reportcardgrade",
            name="final_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("E", "E")],
                max_length=1,
            ),
        ),
    ]
