# Generated by Django 5.1.3 on 2025-12-03 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0016_alter_assignmentdetail_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeentry',
            name='assignment_date',
            field=models.DateField(default=datetime.date(2025, 12, 3)),
        ),
    ]
