# Generated by Django 5.2 on 2025-11-21 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0016_alter_gradeentry_assignment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.datetime(2025, 11, 21, 0, 0)),
        ),
    ]
