# Generated by Django 5.2 on 2025-12-01 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0017_alter_gradeentry_assignment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.date(2025, 12, 1)),
        ),
    ]
