# Generated by Django 5.2 on 2025-12-03 02:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0014_religion_remove_registration_address_and_more"),
        ("gradebook", "0018_alter_gradeentry_assignment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentdetail",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.date(2025, 12, 3)),
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField(blank=True, null=True)),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("S", "Sick"),
                            ("P", "Permit"),
                            ("A", "Absent"),
                            ("L", "Late"),
                        ],
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.student",
                    ),
                ),
            ],
        ),
    ]
