# Generated by Django 5.2 on 2025-12-05 03:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0014_religion_remove_registration_address_and_more"),
        ("gradebook", "0019_alter_assignmentdetail_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcardgrade",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="reportcardgrade",
            name="level",
        ),
        migrations.RemoveField(
            model_name="reportcardgrade",
            name="period",
        ),
        migrations.RemoveField(
            model_name="reportcardgrade",
            name="student",
        ),
        migrations.AddField(
            model_name="reportcardgrade",
            name="teacher_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.date(2025, 12, 5)),
        ),
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Spiritual", "Spiritual Behaviour"),
                            ("Social", "Social Behaviour"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.academicyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RubricIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_text",
                    models.TextField(blank=True, null=True, unique=True),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.rubric",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentReportcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_mid", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.academicyear",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.schoollevel",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.learningperiod",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportcardNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spiritual_char_statement", models.TextField(blank=True, null=True)),
                ("spiritual_char_notes", models.TextField(blank=True, null=True)),
                ("social_statement", models.TextField(blank=True, null=True)),
                ("social_char_notes", models.TextField(blank=True, null=True)),
                ("social_notes", models.TextField(blank=True, null=True)),
                ("homeroom_notes", models.TextField(blank=True, null=True)),
                (
                    "reportcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.studentreportcard",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reportcardgrade",
            name="reportcard",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gradebook.studentreportcard",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StudentRubrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.rubricindicator",
                    ),
                ),
                (
                    "reportcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.studentreportcard",
                    ),
                ),
            ],
        ),
    ]
