# Generated by Django 5.2 on 2025-12-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0020_remove_reportcardgrade_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubric",
            name="index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rubricindicator",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
