# Generated by Django 5.2 on 2025-12-12 09:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0015_gradelevel"),
        ("gradebook", "0021_rubric_index_rubricindicator_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rubric",
            options={"verbose_name": "Rubric", "verbose_name_plural": "Rubrics"},
        ),
        migrations.AlterModelOptions(
            name="rubricindicator",
            options={
                "verbose_name": "Rubric indicator",
                "verbose_name_plural": "Rubric Indicators",
            },
        ),
        migrations.AddField(
            model_name="studentreportcard",
            name="grade_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.gradelevel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.date(2025, 12, 12)),
        ),
        migrations.AlterField(
            model_name="studentrubrics",
            name="score",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")], default=0
            ),
        ),
    ]
