# Generated by Django 5.2 on 2025-12-17 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gradebook",
            "0022_alter_rubric_options_alter_rubricindicator_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(default=datetime.date(2025, 12, 17)),
        ),
    ]
