# Generated by Django 5.2 on 2025-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0023_alter_gradeentry_assignment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeentry",
            name="assignment_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
