# Generated by Django 5.2 on 2025-12-18 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0016_gradelevel_school_level"),
        ("gradebook", "0024_alter_gradeentry_assignment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradeentry",
            name="school_level",
        ),
        migrations.AddField(
            model_name="gradeentry",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="passinggrade",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="studentreportcard",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_level_reportcard",
                to="admission.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="weighting",
            name="level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admission.gradelevel",
            ),
        ),
    ]
