# Generated by Django 5.2 on 2025-12-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0016_gradelevel_school_level"),
        ("gradebook", "0025_remove_gradeentry_school_level_gradeentry_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentreportcard",
            name="grade_level",
        ),
        migrations.AlterField(
            model_name="gradeentry",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admission.gradelevel"
            ),
        ),
        migrations.AlterField(
            model_name="passinggrade",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admission.gradelevel"
            ),
        ),
        migrations.AlterField(
            model_name="studentreportcard",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_level_reportcard",
                to="admission.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="weighting",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admission.gradelevel"
            ),
        ),
    ]
