# Generated by Django 5.2 on 2026-03-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0026_remove_studentreportcard_grade_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rubric",
            name="academic_year",
        ),
        migrations.AlterField(
            model_name="assignmenthead",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name="ReportcardBehaviour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "reportcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.studentreportcard",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.rubric",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StudentRubrics",
        ),
    ]
