# Generated by Django 5.2 on 2026-03-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0027_remove_rubric_academic_year_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportcardBehaviour",
        ),
    ]
