# Generated by Django 5.2 on 2026-03-06 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0017_alter_gradelevel_options_alter_schoollevel_options"),
        ("gradebook", "0029_reportcardbehaviour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcardbehaviour",
            name="rubric",
        ),
        migrations.RemoveField(
            model_name="reportcardbehaviour",
            name="score",
        ),
        migrations.CreateModel(
            name="StudentBehaviourReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "behaviour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.reportcardbehaviour",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.rubric",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.student",
                    ),
                ),
            ],
        ),
    ]
