# Generated by Django 5.2 on 2026-03-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0030_remove_reportcardbehaviour_rubric_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcardbehaviour",
            name="student",
        ),
    ]
