"""
Django settings for django_sis project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-i4rd4lfs2lmi2l8rsuxe(1$pa$7dh#7-o*i###tb)v86!20t@c"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["superdifficult-semitransparently-jamel.ngrok-free.dev", "127.0.0.1", "0.0.0.0:8000"]

INTERNAL_IPS = ["127.0.0.1",]

CSRF_TRUSTED_ORIGINS = [
    "https://superdifficult-semitransparently-jamel.ngrok-free.dev",
]

# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "django_daisy",              #for django-daisy
    # "django.contrib.admin",
    "django_sis.apps.CustomAdminConfig",
    "django.contrib.humanize",   #for django-daisy
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "widget_tweaks",
    "bulk_signals",
    "debug_toolbar",
    "django_extensions",
    "import_export",
    "django_htmx",
    "admission",
    "gradebook",
    "crispy_forms",
    "formtools",
    'simple_history', # django-simple-history
    "slick_reporting", # django-slick-reporting
    "crispy_bootstrap4", # django-slick-reporting
    "rest_framework",
    "rest_framework_api_key"
]

CRISPY_TEMPLATE_PACK = "bootstrap4"
MIDDLEWARE = [
    'simple_history.middleware.HistoryRequestMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_sis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'django_sis', 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_sis.wsgi.application"



# SQLite3
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "django_sisdb.sqlite3",
    }
}


# MySQL, hosted locally with XAMPP
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'djangosis_test', # database name eg-django
#         'USER':'root', # username as root
#         'PASSWORD':'', # password keep empty
#         'HOST':'localhost', # host is localhost
#         'PORT':'3306', # you can find port in xampp control panel(mysql)
# }
# }

# percobaan integrasi db postgresql di railway -nic
# PostgreSQL, thru Railway
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "railway",
#         "USER": "postgres",
#         "PASSWORD": "geiBpfyCEViGgvSBSEapSzmXKsmpywSS",
#         "HOST": "ballast.proxy.rlwy.net",
#         "PORT": "23615",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Jakarta"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static_files/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static_files'),]
STATIC_ROOT = os.path.join(BASE_DIR, 'djangoschool/static_files')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DAISY_SETTINGS = {
    'SITE_TITLE': 'System Administration',  # The title of the site
    'SITE_HEADER': 'SIS Backend Admin',  # Header text displayed in the admin panel
    'INDEX_TITLE': 'Hi, welcome to SIS dashboard',  # The title for the index page of dashboard
    'SITE_LOGO': '/static_files/admin/img/logo_echs.jpeg',  # Path to the logo image displayed in the sidebar
    'EXTRA_STYLES': [],  # List of extra stylesheets to be loaded in base.html (optional)
    'EXTRA_SCRIPTS': [],  # List of extra script URLs to be loaded in base.html (optional)
    'LOAD_FULL_STYLES': True,  # If True, loads full DaisyUI components in the admin (useful if you have custom template overrides)
    'SHOW_CHANGELIST_FILTER': True,  # If True, the filter sidebar will open by default on changelist views
    'DONT_SUPPORT_ME': True, # Hide github link in sidebar footer
    'SIDEBAR_FOOTNOTE': 'ver. 1.0.0', # add footnote to sidebar
    'APPS_REORDER': {
        #Custom configurations for third-party apps that can't be modified directly in their `apps.py`
        'auth': {
            'icon': 'fa-solid fa-person-military-pointing',  # FontAwesome icon for the 'auth' app
            'name': 'Authentication',  # Custom name for the 'auth' app
            'hide': False,  # Whether to hide the 'auth' app from the sidebar (set to True to hide)
            'divider_title': "Authentication Module",  # Divider title for the 'auth' section
        },
        'admission': {
            'icon': 'fa-solid fa-users-gear',  # Custom FontAwesome icon for the 'social_django' app
            'divider_title': "Admission Module",
        },
        'gradebook': {
            'icon': 'fa-solid fa-users-gear',  # Custom FontAwesome icon for the 'social_django' app
            'divider_title': "Gradebook Module",
        },

    },
}


# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         "rest_framework_api_key.permissions.HasAPIKey"
#     ]
# }


#LOGIN_REDIRECT_URL = '/'
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.db.backends': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }